### PR TITLE
css added to the profit and expense pages inside summary

### PR DESCRIPTION
**Pull request by prabhkirat12**
add the p and l css in the summary tab

### CODE REVIEW

**Comment by Two-Ocean** [comment]
Very good additions. CSS looks great. 
Suggestion: Add more bootstrap code in your js file to match the other pages' css

**Comment by vaidik100** [comment]
Your button styling is good, but ensure consistency in terms of size, padding, and font across all buttons. It's good practice to maintain uniformity in styling throughout the application.
Ensure consistent indentation and formatting throughout the codebase for better readability and maintainability.

**Comment by prabhkirat12** [comment]
> Your button styling is good, but ensure consistency in terms of size, padding, and font across all buttons. It's good practice to maintain uniformity in styling throughout the application. Ensure consistent indentation and formatting throughout the codebase for better readability and maintainability.

yeah for that reason i have change the margine to 10 px the top one in the submit button.

**Comment by prabhkirat12** [comment]
> Very good additions. CSS looks great. Suggestion: Add more bootstrap code in your js file to match the other pages' css

Thanks for the review i just want to try a new things coz every page is made in bootstrap so for that reason to explore myself i prefer css more. However, the style is combining with the other pages.

**Pull request merged**
