### PR TITLE
Bartransaction

### PR DESCRIPTION
**Pull request by prabhkirat12**
add this for the userOverview it is responsive and every function is working kindly go through the code

### CODE REVIEW

**Comment by abhishek-2110** [comment]
You've made significant additions and modifications to the UserOverviewPage component, notably including a pie chart for account balances and a bar chart for transaction history. Its working perfectly and showing the chart and graph.

**Comment by prabhkirat12** [comment]
> You've made significant additions and modifications to the UserOverviewPage component, notably including a pie chart for account balances and a bar chart for transaction history. Its working perfectly and showing the chart and graph.

THANKS

**Comment by Two-Ocean** [comment]
Solid additions. 
Possible improvements could be to make less number of commits in bigger scenarios and same amount of changes to not clog up the commits tab. Overall good work as this does not clog it up too much

**Comment by prabhkirat12** [comment]
Thanks for your comment siya the issue for having this much commit was that the client want the transaction to be display in the bar one so for that issue there are that much commits . (for fixing the debit and credit and displaying the account name )

**Comment by vaidik100** [comment]
Refactoring the form submission handling for income and expense transactions improves code clarity and maintainability.
Consider extracting repetitive code into separate functions or utilities to avoid duplication and improve code readability further.
 Ensure consistency in variable naming conventions and documentation style throughout the component for better code maintainability.

**Comment by prabhkirat12** [comment]
> Refactoring the form submission handling for income and expense transactions improves code clarity and maintainability. Consider extracting repetitive code into separate functions or utilities to avoid duplication and improve code readability further. Ensure consistency in variable naming conventions and documentation style throughout the component for better code maintainability.


"I created two functions because the data is distributed into two different graphs. One graph depicts the overall account, while the other one focuses on the transaction part. Both functions have different inputs and outputs. I am open to any other comments."

**Pull request merged**
